name: "Autoformat using Black & isort"

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:


jobs:
  autoformat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:  # https://github.com/stefanzweifel/git-auto-commit-action#checkout-the-correct-branch
            ref: ${{ github.head_ref }}

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install pip modules
        run: pip install black isort

      - name: Run isort 
        run: isort .

      - name: Run Black 
        run: black .

      - name: Commit and push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "auto: format python code"
          git push
